# Generated by Django 2.1.1 on 2018-12-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(choices=[('fresh', 'fresh'), ('cool', 'cool'), ('nice', 'nice')], max_length=200, null=True),
        ),
    ]
