# Generated by Django 2.1.1 on 2018-12-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='short_name',
            new_name='last_name',
        ),
    ]
